/* C ABI for the Temporal sdk-core bridge (mock).
 *
 * In a real project this header would be generated by `cbindgen` from the Rust
 * crate. Here it is hand-written and kept in lockstep with src/lib.rs. */
#ifndef TEMPORAL_BRIDGE_H
#define TEMPORAL_BRIDGE_H

#include <stddef.h>
#include <stdint.h>

/* Opaque handles. */
typedef struct Runtime Runtime;
typedef struct Client Client;
typedef struct Worker Worker;

/* Borrowed bytes (argument direction). */
typedef struct ByteArrayRef {
  const uint8_t *data;
  size_t size;
} ByteArrayRef;

/* Owned bytes (return direction); free with temporal_bridge_byte_array_free. */
typedef struct ByteArray {
  uint8_t *data;
  size_t size;
  size_t cap;
} ByteArray;

/* Completion callbacks. A NULL `fail` means success. */
typedef void (*ClientConnectCallback)(void *user_data, Client *client,
                                       const ByteArray *fail);
typedef void (*WorkerPollCallback)(void *user_data, const ByteArray *activation,
                                    const ByteArray *fail);
typedef void (*WorkerCallback)(void *user_data, const ByteArray *fail);

Runtime *temporal_bridge_runtime_new(void);
void temporal_bridge_runtime_free(Runtime *rt);

void temporal_bridge_client_connect(Runtime *rt, ByteArrayRef target,
                                    void *user_data, ClientConnectCallback cb);
void temporal_bridge_client_free(Client *c);

Worker *temporal_bridge_worker_new(Client *c, ByteArrayRef task_queue);
void temporal_bridge_worker_free(Worker *w);

void temporal_bridge_worker_poll_workflow_activation(Worker *w, void *user_data,
                                                     WorkerPollCallback cb);
void temporal_bridge_worker_complete_workflow_activation(Worker *w,
                                                         ByteArrayRef completion,
                                                         void *user_data,
                                                         WorkerCallback cb);

void temporal_bridge_worker_poll_activity_task(Worker *w, void *user_data,
                                               WorkerPollCallback cb);
void temporal_bridge_worker_complete_activity_task(Worker *w,
                                                   ByteArrayRef completion,
                                                   void *user_data,
                                                   WorkerCallback cb);

void temporal_bridge_byte_array_free(Runtime *rt, ByteArray *bytes);

#endif /* TEMPORAL_BRIDGE_H */
